export { default as Text } from './CustomText/CustomText'
export { default as Drawer } from './Drawer/Drawer'
export * from './IconFont/iconFont'
export { default as BounceLayout } from './Layout/BounceLayout'
export { default as Touchable } from './Touchable/Touchable'
export { widthLoading } from './higherOrderComponents'
export { default as Avatar } from './Avatar/Avatar'
// export { default as Modal } from './Modal'
export { default as TabScreen } from './TabScreen/TabScreen'
export { default as CustomTabNavigator } from './TabScreen/CustomTabNavigator'