module.exports = {
    list: [{
        "ListCoursePreLesson": [],
        "LiveCourseId": 14,
        "TeacherId": 660,
        "CreationTime": "2019-02-15T14:28:20.053",
        "CourseNo": "20190215142820052",
        "CourseName": "该计划开工好看刚好",
        "CourseType": 3,
        "CourseTypeName": "同步课",
        "SubjectId": 9,
        "PhaseId": 2,
        "PhaseName": "初中",
        "GradeId": 7,
        "GradeName": "七年级",
        "CoverPictureUrl": "http://oss.huijiaoketang.com/Rescourse/Material/2019-02-15/rhJDXWzWYr.png",
        "CourseSummary": "规范的合法的韩国放",
        "IsFee": true,
        "Price": 5555.0,
        "ApplyEndTime": "2019-02-15T00:00:00",
        "StudyEndTime": "2019-02-15T00:00:00",
        "MaxJionCount": 12,
        "SearchKey": "规范化风格",
        "CourseDescription": "<p>换个烦得很规范化黑寡妇</p>",
        "IsRelated": true,
        "VirtualApplyCount": 0,
        "ApplyCount": 0,
        "StartLiveDate": "2019-02-23T16:02:00",
        "EndLvieDate": "2019-02-26T16:05:00",
        "TakeClassStartTime": "16:05",
        "TakeClassEndTime": "18:06",
        "TakeClassType": 1,
        "TeacherName": "郑弘",
        "SubjectName": "英语",
        "SellStatus": 1,
        "RelatedPrelessonCount": 4,
        "IsAttention": false,
        "ListKey": ["规范化风格"]
    }, {
        "ListCoursePreLesson": [],
        "LiveCourseId": 13,
        "TeacherId": 660,
        "CreationTime": "2019-02-15T14:24:30.093",
        "CourseNo": "20190215142430091",
        "CourseName": "接口和顾客民和股份1",
        "CourseType": 4,
        "CourseTypeName": "专题课",
        "SubjectId": 9,
        "PhaseId": 2,
        "PhaseName": "初中",
        "GradeId": 9,
        "GradeName": "九年级",
        "CoverPictureUrl": "http://oss.huijiaoketang.com/Rescourse/Material/2019-02-22/NjKpzQafZb.png",
        "CourseSummary": "梵蒂冈的个2",
        "IsFee": true,
        "Price": 1.0,
        "ApplyEndTime": "2019-02-22T00:00:00",
        "StudyEndTime": "2019-02-15T00:00:00",
        "MaxJionCount": 0,
        "SearchKey": "2",
        "CourseDescription": "<p>fv水电费功夫大概对方过后梵蒂冈</p>",
        "IsRelated": true,
        "VirtualApplyCount": 0,
        "ApplyCount": 0,
        "StartLiveDate": null,
        "EndLvieDate": null,
        "TakeClassStartTime": null,
        "TakeClassEndTime": null,
        "TakeClassType": 0,
        "TeacherName": "郑弘",
        "SubjectName": "英语",
        "SellStatus": 0,
        "RelatedPrelessonCount": 1,
        "IsAttention": false,
        "ListKey": ["2"]
    }, {
        "ListCoursePreLesson": [],
        "LiveCourseId": 11,
        "TeacherId": 660,
        "CreationTime": "2019-02-14T15:53:07.727",
        "CourseNo": "20190214155307724",
        "CourseName": "hgffgh",
        "CourseType": 3,
        "CourseTypeName": "同步课",
        "SubjectId": 9,
        "PhaseId": 2,
        "PhaseName": "初中",
        "GradeId": 7,
        "GradeName": "七年级",
        "CoverPictureUrl": "http://oss.huijiaoketang.com/Rescourse/Material/2019-02-14/3eZkyENdJG.png",
        "CourseSummary": "bvcvdsfds f dfs d",
        "IsFee": true,
        "Price": 444.0,
        "ApplyEndTime": "2019-02-14T00:00:00",
        "StudyEndTime": "2019-02-14T00:00:00",
        "MaxJionCount": 11,
        "SearchKey": "fg#fg dsfg",
        "CourseDescription": "<p>xcdvgdg&nbsp;</p>",
        "IsRelated": false,
        "VirtualApplyCount": 0,
        "ApplyCount": 0,
        "StartLiveDate": null,
        "EndLvieDate": null,
        "TakeClassStartTime": null,
        "TakeClassEndTime": null,
        "TakeClassType": 0,
        "TeacherName": "郑弘",
        "SubjectName": "英语",
        "SellStatus": 0,
        "RelatedPrelessonCount": 0,
        "IsAttention": false,
        "ListKey": ["fg", "fg dsfg"]
    }, {
        "ListCoursePreLesson": [],
        "LiveCourseId": 10,
        "TeacherId": 660,
        "CreationTime": "2019-01-30T14:54:43.617",
        "CourseNo": "20190130145443615",
        "CourseName": "sample string 5",
        "CourseType": 3,
        "CourseTypeName": "同步课",
        "SubjectId": 9,
        "PhaseId": 2,
        "PhaseName": "初中",
        "GradeId": 7,
        "GradeName": "七年级",
        "CoverPictureUrl": "http://oss.huijiaoketang.com/Rescourse/Material/2019-02-14/3eZkyENdJG.png",
        "CourseSummary": "sample string 11",
        "IsFee": true,
        "Price": 13.1,
        "ApplyEndTime": "2019-01-28T09:51:52.2",
        "StudyEndTime": "2019-01-28T09:51:52.2",
        "MaxJionCount": 16,
        "SearchKey": "sample string 17",
        "CourseDescription": "sample string 18",
        "IsRelated": true,
        "VirtualApplyCount": 0,
        "ApplyCount": 20,
        "StartLiveDate": null,
        "EndLvieDate": null,
        "TakeClassStartTime": null,
        "TakeClassEndTime": null,
        "TakeClassType": 0,
        "TeacherName": "郑弘",
        "SubjectName": "英语",
        "SellStatus": 4,
        "RelatedPrelessonCount": 2,
        "IsAttention": false,
        "ListKey": ["sample string 17"]
    }, {
        "ListCoursePreLesson": [],
        "LiveCourseId": 9,
        "TeacherId": 660,
        "CreationTime": "2019-01-30T14:54:42.033",
        "CourseNo": "20190130145442032",
        "CourseName": "sample string 5",
        "CourseType": 3,
        "CourseTypeName": "同步课",
        "SubjectId": 9,
        "PhaseId": 2,
        "PhaseName": "初中",
        "GradeId": 7,
        "GradeName": "七年级",
        "CoverPictureUrl": "http://oss.huijiaoketang.com/Rescourse/Material/2019-02-14/3eZkyENdJG.png",
        "CourseSummary": "sample string 11",
        "IsFee": false,
        "Price": 13.1,
        "ApplyEndTime": "2019-01-28T09:51:52.2",
        "StudyEndTime": "2019-01-28T09:51:52.2",
        "MaxJionCount": 16,
        "SearchKey": "sample string 17",
        "CourseDescription": "sample string 18",
        "IsRelated": true,
        "VirtualApplyCount": 0,
        "ApplyCount": 21,
        "StartLiveDate": null,
        "EndLvieDate": null,
        "TakeClassStartTime": null,
        "TakeClassEndTime": null,
        "TakeClassType": 0,
        "TeacherName": "郑弘",
        "SubjectName": "英语",
        "SellStatus": 3,
        "RelatedPrelessonCount": 2,
        "IsAttention": false,
        "ListKey": ["sample string 17"]
    }, {
        "ListCoursePreLesson": [],
        "LiveCourseId": 8,
        "TeacherId": 660,
        "CreationTime": "2019-01-30T14:54:41.39",
        "CourseNo": "20190130145441390",
        "CourseName": "sample string 5",
        "CourseType": 3,
        "CourseTypeName": "同步课",
        "SubjectId": 9,
        "PhaseId": 2,
        "PhaseName": "初中",
        "GradeId": 7,
        "GradeName": "七年级",
        "CoverPictureUrl": "http://oss.huijiaoketang.com/Rescourse/Material/2019-02-14/3eZkyENdJG.png",
        "CourseSummary": "sample string 11",
        "IsFee": false,
        "Price": 13.1,
        "ApplyEndTime": "2019-01-28T09:51:52.2",
        "StudyEndTime": "2019-01-28T09:51:52.2",
        "MaxJionCount": 16,
        "SearchKey": "sample string 17",
        "CourseDescription": "sample string 18",
        "IsRelated": true,
        "VirtualApplyCount": 0,
        "ApplyCount": 21,
        "StartLiveDate": null,
        "EndLvieDate": null,
        "TakeClassStartTime": null,
        "TakeClassEndTime": null,
        "TakeClassType": 0,
        "TeacherName": "郑弘",
        "SubjectName": "英语",
        "SellStatus": 2,
        "RelatedPrelessonCount": 2,
        "IsAttention": false,
        "ListKey": ["sample string 17"]
    }, {
        "ListCoursePreLesson": [],
        "LiveCourseId": 7,
        "TeacherId": 660,
        "CreationTime": "2019-01-30T14:54:38.21",
        "CourseNo": "20190130145438209",
        "CourseName": "sample string 5",
        "CourseType": 3,
        "CourseTypeName": "同步课",
        "SubjectId": 9,
        "PhaseId": 2,
        "PhaseName": "初中",
        "GradeId": 7,
        "GradeName": "七年级",
        "CoverPictureUrl": "http://oss.huijiaoketang.com/Rescourse/Material/2019-02-14/3eZkyENdJG.png",
        "CourseSummary": "sample string 11",
        "IsFee": true,
        "Price": 13.1,
        "ApplyEndTime": "2019-01-28T09:51:52.2",
        "StudyEndTime": "2019-01-28T09:51:52.2",
        "MaxJionCount": 16,
        "SearchKey": "sample string 17",
        "CourseDescription": "sample string 18",
        "IsRelated": true,
        "VirtualApplyCount": 0,
        "ApplyCount": 24,
        "StartLiveDate": null,
        "EndLvieDate": null,
        "TakeClassStartTime": null,
        "TakeClassEndTime": null,
        "TakeClassType": 0,
        "TeacherName": "郑弘",
        "SubjectName": "英语",
        "SellStatus": 3,
        "RelatedPrelessonCount": 2,
        "IsAttention": false,
        "ListKey": ["sample string 17"]
    }]
}